[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache = true
cache_path = 'cache'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
